"""Type stubs for utility functions."""

import hashlib
import os
import subprocess
from pathlib import Path
from typing import Any

def resolve_workspace(workspace_path: str | None = None) -> str: ...
def hash_workspace_path(workspace_path: str) -> str: ...
def get_project_db_path(workspace_path: str | None = None) -> Path: ...
def get_master_db_path() -> Path: ...
def validate_description_length(description: str | None) -> None: ...
def ensure_absolute_path(path: str) -> str: ...
def get_workspace_metadata(workspace_path: str | None = None) -> dict[str, str | None]: ...
def _get_git_root(workspace_path: str) -> str | None: ...
def _get_project_name(workspace_path: str) -> str: ...
